In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'2.4.0'

### **Constantes**

In [3]:
tensor = tf.constant([[23, 4], [32, 51]])

In [4]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [5]:
tensor.shape

TensorShape([2, 2])

In [6]:
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [7]:
numpy_tensor = np.array([[23, 4], [32, 51]])

In [9]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### **Variáveis**

In [11]:
tf_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [12]:
tf_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [13]:
tf_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [14]:
tf_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

### **Operações com vetores**

In [15]:
tensor = tf.constant([[23, 4], [32, 51]])

In [16]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25,  6],
       [34, 53]], dtype=int32)>

In [17]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[115,  20],
       [160, 255]], dtype=int32)>

**Funções numpy com o tensorflow**

In [18]:
np.square(tensor)

array([[ 529,   16],
       [1024, 2601]], dtype=int32)

In [19]:
np.sqrt(tensor)

array([[4.79583152, 2.        ],
       [5.65685425, 7.14142843]])

In [20]:
np.dot(tensor, tensor)

array([[ 657,  296],
       [2368, 2729]], dtype=int32)

### **Strings no Tensorflow 2.0**

In [21]:
tf_string = tf.constant("Tensorflow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [23]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [24]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [25]:
tf_string_array = tf.constant(["Tensorflow", "Deep Learning", "AI"])

In [26]:
for string in tf_string_array:
    print(string)

tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)
